* took out getAttribute methods in SComponent...don't make the API dirty * committing change to makeCG method by Christian Humer. Bugfix for tomcat   startup problem (NoClassDefFoundError)
git-svn-id: https://j-wings.svn.sourceforge.net/svnroot/j-wings/trunk/wings2@2092 c8af5dc8-8010-0410-93ac-e0f74e17e1d8